class Bag{
  ArrayList<Tile> bagged = new ArrayList<Tile>();
  Tile A1 = new A();
  bagged.add(A1);
  Tile A2 = new A();
  bagged.add(A2);
  Tile A3 = new A();
  bagged.add(A3);
  Tile A4 = new A();
  bagged.add(A4);
  Tile A5 = new A();
  bagged.add(A5);
  Tile A6 = new A();
  bagged.add(A6);
  Tile A7 = new A();
  bagged.add(A7);
  Tile A8 = new A();
  bagged.add(A8);
  Tile A9 = new A();
  bagged.add(A9);
    Tile B1 = new B();
  bagged.add(B1);
  Tile B2 = new B();
  bagged.add(B2);
  Tile C1 = new C();
  bagged.add(C1);
  Tile C2 = new C();
  bagged.add(C2);
  Tile D1 = new D();
  bagged.add(D1);
  Tile D2 = new D();
  bagged.add(D2);
  Tile D3 = new D();
  bagged.add(D3);
  Tile D4 = new D();
  bagged.add(D4);
  Tile E1 new E();
  bagged.add(E1);
  Tile E2 = new E();
  bagged.add(E2);
  Tile E3 = new E();
  bagged.add(E3);
  Tile E4 = new E();
  bagged.add(E3);
  Tile E5 = new E();
  bagged.add(E5);
  Tile E6 = new E();
  bagged.add(E6);
  Tile E7 = new E();
  bagged.add(E7);
  Tile E8 = new E();
  bagged.add(E8);
  Tile E9 = new E();
  bagged.add(E9);
  Tile E10 = new E();
  bagged.add(E10);
  Tile E11 = new E();
  bagged.add(E11);
  Tile E12 = new E();
  bagged.add(E12);
  
  Tile F1 = new F();
  bagged.add(F1);
  Tile F2 = new F();
  bagged.add(F2);
  Tile G1 = new G();
  bagged.add(G1);
  Tile G2 = new G2();
  bagged.add(G2);
  Tile G3 = new G();
  bagged.add(G3);
  Tile H1 = new H();
  bagged.add(H1);
  Tile H2 = new H();
  bagged.add(H2);
  Tile H3 = new H3();
  bagged.add(H3);
  
  
}